openapi: 3.0.3
info:
  title: "sample"
  version: "1.0.0"
paths:
  /todo/{id}:
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
    get:
      operationId: getTodo
      summary: Get todo
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Todo"
components:
  schemas:
    Todo:
      type: object
      properties:
        id: 
          type: string
        title:
          type: string
        body:
          type: string
        completed:
          type: boolean
      required:
        - id
        - title
        - body
        - completed
      example:
        id: 'testID'
        title: 'Todo title'
        body: 'Todo body'
        completed: false



  